export const SITE_ROUTES = {
  home: "/",
  aboutUs: "/about-us",
  advertisers: "/advertisers",
  ourPartners: "/our-partners",
  ppc: "/ppc",
  seo: "/seo",
  retargeting: "/retargeting",
  displayAdvertising: "/display-advertising",
  connectedTv: "/connected-tv",
  dsp: "/dsp",
  webdev: "/webdev",
  influencerMarketing: "/influencer-marketing",
  orm: "/orm",
  conversionLedGrowth: "/conversion-led-growth",
  videoNativeAds: "/video-native-ads",
  affiliatesPublisherMarketing: "/affiliates-publisher-marketing",
  privacyCookiesPolicy: "/privacy-cookies-policy",
  complaintsPolicy: "/complaints-policy",
  gdprDataProtection: "/gdpr-data-protection",
  codeOfConduct: "/code-of-conduct",
  modernSlaveryStatement: "/modern-slavery-statement",
  legalNoticeWebsiteTerms: "/legal-notice-website-terms",
} as const;
